apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: efehk5le1-python 
  janus-idp.io/tekton: efehk5le1-python
  backstage.io/kubernetes-id: efehk5le1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: efehk5le1-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml