apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: efehk5le1-python
  janus-idp.io/tekton: efehk5le1-python
  backstage.io/kubernetes-id: efehk5le1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: efehk5le1-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
