apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: efehk5le1-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: efehk5le1-python 
  name: efehk5le1-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: efehk5le1-python 
